//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticketing.Framework.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardType
    {
        public CardType()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int CardTypeId { get; set; }
        public string CardType1 { get; set; }
        public bool status { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
