//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticketing.Framework.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPerformanceMapping2
    {
        public int ID { get; set; }
        public int OderId { get; set; }
        public int PerformanceId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Performance Performance { get; set; }
    }
}
