//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticketing.Framework.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public Performance()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int PerformanceId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> TotalTickets { get; set; }
        public bool status { get; set; }
        public string EventName { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
